Repository zowe/zlux-platform, pull requests merged in 2024-08, with the labels that each got.

#105 Implement lookup from PR 308 of zlux-app-server
  base/src/plugin-manager/plugin.ts
  interface/src/index.d.ts
Labels: size/S

#104 Exclude wrong version of angular plugins by checking entrypoint content
  base/src/plugin-manager/plugin-manager.ts
  base/src/plugin-manager/plugin.ts
  interface/src/index.d.ts
Labels: size/M

#106 Update build workflow
  .github/workflows/build-core.yml
Labels: size/XS
